package com.reyes.model;
// Generated 06-may-2016 10:26:29 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String nomUsuario;
     private String passUsuario;

    public Usuario() {
    }

    public Usuario(String nomUsuario, String passUsuario) {
       this.nomUsuario = nomUsuario;
       this.passUsuario = passUsuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNomUsuario() {
        return this.nomUsuario;
    }
    
    public void setNomUsuario(String nomUsuario) {
        this.nomUsuario = nomUsuario;
    }
    public String getPassUsuario() {
        return this.passUsuario;
    }
    
    public void setPassUsuario(String passUsuario) {
        this.passUsuario = passUsuario;
    }




}


